
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autohealer.stakater.com
  resources:
  - conditionsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autohealer.stakater.com
  resources:
  - conditionsets/finalizers
  verbs:
  - update
- apiGroups:
  - autohealer.stakater.com
  resources:
  - conditionsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autohealer.stakater.com
  resources:
  - ntcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autohealer.stakater.com
  resources:
  - ntcs/finalizers
  verbs:
  - update
- apiGroups:
  - autohealer.stakater.com
  resources:
  - ntcs/status
  verbs:
  - get
  - patch
  - update
