apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-cert
  name: busybox-cert
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-cert
  strategy: {}
  template:
    metadata:
      labels:
        app: busybox-cert
    spec:
      containers:
        - image: busybox
          imagePullPolicy: Never
          name: busybox
          resources: {}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          args:
            - sleep
            - "1000"
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert